"""empty message

Revision ID: 4430434157dc
Revises: dda0d0a75c19
Create Date: 2021-11-29 12:20:23.586435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4430434157dc'
down_revision = 'dda0d0a75c19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
