"""add [delete] column to users table

Revision ID: 5ae9d3882a0a
Revises: f7541d426d4d
Create Date: 2021-11-26 16:22:48.138689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ae9d3882a0a'
down_revision = 'f7541d426d4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###
