"""empty message

Revision ID: dda0d0a75c19
Revises: 5ae9d3882a0a
Create Date: 2021-11-26 16:42:11.770472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda0d0a75c19'
down_revision = '5ae9d3882a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('inactivate', sa.Boolean(), nullable=True))
    op.drop_column('users', 'delete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('delete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'inactivate')
    # ### end Alembic commands ###
